### ISSUE TITLE
Process 'command 'git'' finished with non-zero exit value 128

### ISSUE THREAD

**Issue by AditRosnah** [kibotu/net.kibotu.android.deviceinfo#19]

**Comment by kibotu** [comment]
it means you haven't added a git commit yet, did you download the project as zip file instead of a `git clone https://github.com/kibotu/net.kibotu.android.deviceinfo.git` by any chance?

other than that, the gradle tasks regarding versioning can be commented out, it's only for automatic library versioning and are not required

**Comment by AditRosnah** [comment]
Thank you very much. Yes, the first time i downloaded the project as zip, now that i clone the project i get this error
error: cannot find symbol method with(MainApplication)
